name: Code Quality

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "news/**"
      - "*.md"
  push:
    branches: ["master", "main"]
    paths-ignore:
      - "docs/**"
      - "news/**"
      - "*.md"

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: 3.12
      - uses: pre-commit/action@main
